{% set version = "2.0.1" %}
{% set commit = "0f1f82cdb9e9540d9c73be46034aaa4f89f82235" %}

package:
  name: pymdwizard
  version: {{ version }}

source:
  url: https://github.com/usgs/fort-pymdwizard/archive/{{ commit }}.tar.gz
  sha256: e864dd321ac40b5f368bbc6b10b85ae74af6d6d09fdab9ad8687ed88fa536d47

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - requests
    - lxml
    - defusedxml
    - pandas
    - jupyter
    - gdal 2.1.*
    - geopandas
    - pyqt >=5.0
    - xlrd
    - python-docx
    - habanero

test:
  imports:
    - pymdwizard

about:
  home: https://github.com/usgs/fort-pymdwizard
  license: CC0 4.0
  license_file: LICENSE.md
  summary: 'A CSDGM Metadata Editor.'

extra:
  recipe-maintainers:
    - ocefpaf
