{% set version = "2.0.4" %}

package:
  name: pymdwizard
  version: {{ version }}

source:
  url: https://github.com/usgs/fort-pymdwizard/releases/download/v{{ version }}/pymdwizard-{{ version }}.tar.gz
  sha256: ad7a33305f519668caada07c871028198499c5818eaae0bbebdf4e07773a02cc

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - lxml
    - defusedxml
    - pandas
    - jupyter
    - gdal 2.2.*
    - geopandas
    - pyqt >=5.0
    - xlrd
    - python-docx
    - habanero

test:
  imports:
    - pymdwizard

about:
  home: https://github.com/usgs/fort-pymdwizard
  license: CC0 4.0
  license_file: LICENSE.md
  summary: 'A CSDGM Metadata Editor.'

extra:
  recipe-maintainers:
    - ocefpaf
