{% set version = "2.0.6" %}

package:
  name: pymdwizard
  version: {{ version }}

source:
  url: https://github.com/usgs/fort-pymdwizard/releases/download/v{{ version }}/pymdwizard-{{ version }}.tar.gz
  sha256: acbeb4dadb76f7d69701ccea95bd62311cb932a9ddd34303dd39958f75c734e6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - lxml
    - defusedxml
    - pandas
    - jupyter
    - gdal
    - geopandas
    - pyqt
    - xlrd
    - python-docx
    - habanero

test:
  imports:
    - pymdwizard

about:
  home: https://github.com/usgs/fort-pymdwizard
  license: CC0-4.0
  license_file: LICENSE.md
  summary: 'A CSDGM Metadata Editor'

extra:
  recipe-maintainers:
    - ocefpaf
