{% set version = "2.0.1" %}

package:
  name: pymdwizard
  version: {{ version }}

source:
  url: https://github.com/usgs/fort-pymdwizard/releases/download/v{{ version }}/pymdwizard-{{ version }}.tar.gz
  sha256: c4d0476ad16a2ddf47a89e048b9e42a8f29e0156c9ef5e77bd9faae2bae62a13 

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - lxml
    - defusedxml
    - pandas
    - jupyter
    - gdal 2.2.*
    - geopandas
    - pyqt >=5.0
    - xlrd
    - python-docx
    - habanero

test:
  imports:
    - pymdwizard

about:
  home: https://github.com/usgs/fort-pymdwizard
  license: CC0 4.0
  license_file: LICENSE.md
  summary: 'A CSDGM Metadata Editor.'

extra:
  recipe-maintainers:
    - ocefpaf
