travis:
  secure:
    BINSTAR_TOKEN: Ssuq+UvmadOPHP4Sx6daPvTeUzlBDtOVL8ZXw+2Oc2ayHtknbisn3yAHo1zrU7VwEW2OyJPKn13n+1uGturPxe1MzkSRMVJ9wg/0mWhxIwv/JQlPSf6TmRd5oiCWECOnqicFk24EOv/W5iJLMDd+a9MRVfS1Z15/k0evCCC1yjjjlwjoawX++63YWEZI4LNDGfNSV9re+H/PFDEMtMl2aIq1lUFtvrOvo5Iv+ahiDwVwuGA10+ZBuJl969yuSnNBGHjcwF5ifCt3+v42VTx1XY/JbQgbcmTyl/uHQqt8VhRUOIvm/i+AGFQN7pXyzeg79bn6x2Ul1Op2X4DRtNGqz6tuW+XXSqhiUwEQu3le8vlR/sMksFF4WF8jTagoulNuMAsFVBZVP3yWrbn1ZvgzkG0JDItItwac+0qLul6XuMDfgZfQKTnouMFn+PvrR1laJyAclB2/I+I6a/8oPX4OxVZqUVhBVtttI0al4Onz9rQq7hsnvmu+qrtCtL5pSYcEiKcK6xmrVw3rUarD94/8Wexg+VsGYy7EcAhhBaRG24eThtsBhrH8hh+4CppbYXlyFaRivtzwYlXa3r8C11JGBN59BXrYB+9YWI+19dO/ABmqReWLK6HGiciyK4MiZ+ElrlYRVDAk8Axs07owHkXXuHc783lFixd06oTHq8Nq4pA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
