travis:
  secure:
    BINSTAR_TOKEN: N+G0ejQYTTLAMCloL1Him59yrR89g5wM4yPtjMV9fD+mRA6v67Uey8Q/MUrWJRLhPyQ8bd/VvkwKasDRJqYj3FyiByYicaw5WvChenwLdwcX1BreIKXABhP7xX7bcRbEwdJS4NL6oE5+910Fd5qWibWC+CFv8LrBw0xgBy8nMH/Qk/SUEeO2OUMDPZdwhy1lXiK3ZqKIT95Fc1aTwZVLrC8S3nwNtAtb4ASAcWxdVGtHKaAEdgTJx8guX4Bd6etzlQ9tcreRwpsL1Sd2vrIIHAIDEMG9TOoCfbRWPPEyWuyYFdDHflY/wtO6WIaxfr3EPBZUklMVefN3tdXqBiYSek2oCMzdTzNxp3fZjFpNHp0DpZfJhxYsvc4eQrD9uu7HBVfyLuIhHSe/JhML09k4TaEmrFdSfbOF/3sz8oE8k3CJrkGstGWwXZVixgAUOb4r2JQRF/9lHKBcNexLHKr6yRUHe0oKjXGzTuMlhsYPI4P1zsQrX+pfSuwDxaCwZC65i04FD1PlzCqpJ8kOsjSCfBurn+M1HLDuT7at2o63fgWyG+xHpkzjfTwqE/3atDyCZf1Y49NLQX9Bh+MPv880q8R2adXLnN56akwO+cOMTv9lcHyQYf/30XzNoIx0EdX/yJNF1F9ZiSTqnmy+q1hbRLeDV6+enFkCalAbHDBNhWA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
